const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electron', {
    onUpdateAvailable: (cb) => ipcRenderer.on('update-available', (e, info) => cb(info)),
    onUpdateProgress: (cb) => ipcRenderer.on('update-progress', (e, pct) => cb(pct)),
    onUpdateDownloaded: (cb) => ipcRenderer.on('update-downloaded', cb),
    login: (credentials) => ipcRenderer.invoke('login-user', credentials),
    launch: (options) => ipcRenderer.invoke('launch-game', options),
    checkUpdate: () => ipcRenderer.invoke('check-update'),
    downloadUpdate: () => ipcRenderer.invoke('download-update'),
    minimize: () => ipcRenderer.send('minimize'),
    maximize: () => ipcRenderer.send('maximize'),
    close: () => ipcRenderer.send('close'),
    openExternal: (url) => ipcRenderer.invoke('open-external', url), // New
    onLog: (callback) => ipcRenderer.on('log', (event, msg) => callback(msg)),
    onProgress: (callback) => ipcRenderer.on('progress', (event, data) => callback(data)),
    onInstallProgress: (callback) => ipcRenderer.on('install-progress', (event, data) => callback(data)),
    installModpack: (data) => ipcRenderer.invoke('install-modpack', data),
    installContent: (data) => ipcRenderer.invoke('install-content', data),
    getInstanceMods: (path) => ipcRenderer.invoke('get-instance-mods', path),
    getInstanceContent: (path) => ipcRenderer.invoke('get-instance-content', path),
    getServers: (instPath) => ipcRenderer.invoke('get-servers', instPath),
    pingServer: (data) => ipcRenderer.invoke('ping-server', data),
    toggleMod: (path, fileName, enable, subDir) => ipcRenderer.invoke('toggle-mod', path, fileName, enable, subDir),
    deleteContentFile: (data) => ipcRenderer.invoke('delete-content-file', data),
    getScreenshots: (path) => ipcRenderer.invoke('get-screenshots', path),
    getWorlds: (path) => ipcRenderer.invoke('get-worlds', path),
    saveScreenshot: (path, fileName, data) => ipcRenderer.invoke('save-screenshot', path, fileName, data),
    deleteScreenshot: (path, fileName) => ipcRenderer.invoke('delete-screenshot', path, fileName),
    saveWorldSettings: (worldPath, settings) => ipcRenderer.invoke('save-world-settings', worldPath, settings),
    openFileDialog: (options) => ipcRenderer.invoke('open-file-dialog', options),
    installLocalMrpack: (data) => ipcRenderer.invoke('install-local-mrpack', data),
    installLocalCurseForge: (data) => ipcRenderer.invoke('install-local-curseforge', data),
    scanLauncherInstances: (data) => ipcRenderer.invoke('scan-launcher-instances', data),
    importLauncherInstance: (data) => ipcRenderer.invoke('import-launcher-instance', data),
    installHexaInstance: (data) => ipcRenderer.invoke('install-hexa-instance', data),
    deleteInstance: (folderName) => ipcRenderer.invoke('delete-instance', folderName),
    onGameStart: (cb) => ipcRenderer.on('game-start', (e, data) => cb(data)),
    onGameExit: (callback) => ipcRenderer.on('game-exit', (event, code) => callback(code)),
    stopGame: () => ipcRenderer.invoke('stop-game'),
    openFolder: (folder) => ipcRenderer.invoke('open-folder', folder),
    createInstance: (data) => ipcRenderer.invoke('create-instance', data),
    applyCustomSkinLoader: (data) => ipcRenderer.invoke('apply-custom-skin-loader', data),
    fetchUsers: () => ipcRenderer.invoke('fetch-users'),
    addFriend: (username) => ipcRenderer.invoke('add-friend', username),
    fetchFriends: () => ipcRenderer.invoke('fetch-friends'),
    acceptFriend: (username) => ipcRenderer.invoke('accept-friend', username),
    rejectFriend: (friendId) => ipcRenderer.invoke('reject-friend', friendId),
    removeFriend: (friendId) => ipcRenderer.invoke('remove-friend', friendId),
    getMessages: (friendId) => ipcRenderer.invoke('get-messages', friendId),
    sendMessage: (friendId, message, replyTo) => ipcRenderer.invoke('send-message', {friendId, message, replyTo}),
    editMessage: (msgId, newContent) => ipcRenderer.invoke('edit-message', {msgId, newContent}),
    deleteMessage: (msgId) => ipcRenderer.invoke('delete-message', msgId),
    reactDmMessage: (msgId, emoji) => ipcRenderer.invoke('react-dm-message', {msgId, emoji}),
    fetchImageBase64: (url) => ipcRenderer.invoke('fetch-image-base64', url),
    uploadChatScreenshot: (data) => ipcRenderer.invoke('upload-chat-screenshot', data),
    getGlobalMessages: () => ipcRenderer.invoke('get-global-messages'),
    sendGlobalMessage: (message, replyTo) => ipcRenderer.invoke('send-global-message', message, replyTo),
    deleteGlobalMessage: (msgId) => ipcRenderer.invoke('delete-global-message', msgId),
    editGlobalMessage: (msgId, newContent) => ipcRenderer.invoke('edit-global-message', { msgId, newContent }),
    pinGlobalMessage: (msgId, pinned) => ipcRenderer.invoke('pin-global-message', { msgId, pinned }),
    reactGlobalMessage: (msgId, emoji) => ipcRenderer.invoke('react-global-message', { msgId, emoji }),
    getMyDbId: () => ipcRenderer.invoke('get-my-db-id'),
    getMyRole: () => ipcRenderer.invoke('get-my-role'),
    fetchRoleColors: () => ipcRenderer.invoke('fetch-role-colors'),
    fetchUsers: () => ipcRenderer.invoke('fetch-users'),
    moderationSanction: (payload) => ipcRenderer.invoke('moderation-sanction', payload),
    moderationUnsanction: (payload) => ipcRenderer.invoke('moderation-unsanction', payload),
    getHexaMessages: () => ipcRenderer.invoke('get-hexa-messages'),
    checkMySanctions: () => ipcRenderer.invoke('check-my-sanctions'),
    fetchUserProfile: (userId, bypassCache) => ipcRenderer.invoke('fetch-user-profile', userId, bypassCache),
    saveProfileBio: (bio) => ipcRenderer.invoke('save-profile-bio', bio),
    saveProfileBanner: (bannerDataUrl) => ipcRenderer.invoke('save-profile-banner', { bannerDataUrl }),
    saveProfileBg: (bg) => ipcRenderer.invoke('save-profile-bg', bg),
    getRecentActivity: (userId) => ipcRenderer.invoke('get-recent-activity', userId),
    getAppVersion: () => ipcRenderer.invoke('get-app-version'),
    getSettings: () => ipcRenderer.invoke('get-settings'),
    saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
    saveInstanceBanner: (folderName, url) => ipcRenderer.invoke('save-instance-banner', { folderName, url }),
    getInstanceBanner: (folderName) => ipcRenderer.invoke('get-instance-banner', folderName),
    wardrobeGetSlot: (username, slotId, type) => ipcRenderer.invoke('wardrobe-get-slot', { username, slotId, type }),
    wardrobeSaveSlot: (username, slotId, type, fileBase64) => ipcRenderer.invoke('wardrobe-save-slot', { username, slotId, type, fileBase64 }),
    wardrobeDeleteSlot: (username, slotId) => ipcRenderer.invoke('wardrobe-delete-slot', { username, slotId }),
    wardrobeGetNames: (username) => ipcRenderer.invoke('wardrobe-get-names', { username }),
    wardrobeSaveNames: (username, names) => ipcRenderer.invoke('wardrobe-save-names', { username, names }),
    changeUsername: (newUsername, totpCode) => ipcRenderer.invoke('change-username', newUsername, totpCode),
    toggleBadgeDisplay: (badgeId, displayed) => ipcRenderer.invoke('toggle-badge-display', { badgeId, displayed }),
    getAllUserBadges: () => ipcRenderer.invoke('get-all-user-badges'),
    setShowRoleBadge: (show) => ipcRenderer.invoke('set-show-role-badge', show),
    // Cosmetics
    cosmeticsGetInventory: () => ipcRenderer.invoke('cosmetics-get-inventory'),
    cosmeticsEquip: (cosmeticId, equipped) => ipcRenderer.invoke('cosmetics-equip', { cosmeticId, equipped }),
    cosmeticsGetCatalog: () => ipcRenderer.invoke('cosmetics-get-catalog'),
    cosmeticsGrant: (username, cosmeticId) => ipcRenderer.invoke('cosmetics-grant', { username, cosmeticId }),
    cosmeticsRevoke: (username, cosmeticId) => ipcRenderer.invoke('cosmetics-revoke', { username, cosmeticId }),
    cosmeticsAdminLookup: (username) => ipcRenderer.invoke('cosmetics-admin-lookup', username),
    // Admin — roles & badges
    adminSetRole: (username, role) => ipcRenderer.invoke('admin-set-role', { username, role }),
    adminGrantBadge: (username, badgeId) => ipcRenderer.invoke('admin-grant-badge', { username, badgeId }),
    adminRevokeBadge: (username, badgeId) => ipcRenderer.invoke('admin-revoke-badge', { username, badgeId }),
    adminGetBadgesCatalog: () => ipcRenderer.invoke('admin-get-badges-catalog'),
    getInstancePlaytime: (folderName) => ipcRenderer.invoke('get-instance-playtime', folderName),
    onInstancePlaytimeRefresh: (cb) => ipcRenderer.on('instance-playtime-refresh', (e, folder) => cb(folder)),

    onAuthSuccess: (cb) => ipcRenderer.on('auth-success', (e, user) => cb(user)),
    onAuthError:   (cb) => ipcRenderer.on('auth-error',   (e, err)  => cb(err)),
    verify2fa:  (data) => ipcRenderer.invoke('verify-2fa', data),
    setup2fa:   ()     => ipcRenderer.invoke('setup-2fa'),
    enable2fa:  (code) => ipcRenderer.invoke('enable-2fa', code),
    disable2fa: (code) => ipcRenderer.invoke('disable-2fa', code),
});

