const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electron', {
    onUpdateAvailable: (cb) => ipcRenderer.on('update-available', (e, info) => cb(info)),
    onUpdateProgress: (cb) => ipcRenderer.on('update-progress', (e, pct) => cb(pct)),
    onUpdateDownloaded: (cb) => ipcRenderer.on('update-downloaded', cb),
    login: (credentials) => ipcRenderer.invoke('login-user', credentials),
    launch: (options) => ipcRenderer.invoke('launch-game', options),
    checkUpdate: () => ipcRenderer.invoke('check-update'),
    downloadUpdate: () => ipcRenderer.invoke('download-update'),
    minimize: () => ipcRenderer.send('minimize'),
    maximize: () => ipcRenderer.send('maximize'),
    close: () => ipcRenderer.send('close'),
    onLog: (callback) => ipcRenderer.on('log', (event, msg) => callback(msg)),
    onProgress: (callback) => ipcRenderer.on('progress', (event, data) => callback(data)),
    onInstallProgress: (callback) => ipcRenderer.on('install-progress', (event, data) => callback(data)),
    installModpack: (data) => ipcRenderer.invoke('install-modpack', data),
    installContent: (data) => ipcRenderer.invoke('install-content', data),
    getInstanceMods: (path) => ipcRenderer.invoke('get-instance-mods', path),
    getInstanceContent: (path) => ipcRenderer.invoke('get-instance-content', path),
    getServers: (instPath) => ipcRenderer.invoke('get-servers', instPath),
    pingServer: (data) => ipcRenderer.invoke('ping-server', data),
    toggleMod: (path, fileName, enable, subDir) => ipcRenderer.invoke('toggle-mod', path, fileName, enable, subDir),
    deleteContentFile: (data) => ipcRenderer.invoke('delete-content-file', data),
    getScreenshots: (path) => ipcRenderer.invoke('get-screenshots', path),
    getWorlds: (path) => ipcRenderer.invoke('get-worlds', path),
    saveScreenshot: (path, fileName, data) => ipcRenderer.invoke('save-screenshot', path, fileName, data),
    deleteScreenshot: (path, fileName) => ipcRenderer.invoke('delete-screenshot', path, fileName),
    saveWorldSettings: (worldPath, settings) => ipcRenderer.invoke('save-world-settings', worldPath, settings),
    openFileDialog: (options) => ipcRenderer.invoke('open-file-dialog', options),
    installLocalMrpack: (data) => ipcRenderer.invoke('install-local-mrpack', data),
    installLocalCurseForge: (data) => ipcRenderer.invoke('install-local-curseforge', data),
    scanLauncherInstances: (data) => ipcRenderer.invoke('scan-launcher-instances', data),
    importLauncherInstance: (data) => ipcRenderer.invoke('import-launcher-instance', data),
    installHexaInstance: (data) => ipcRenderer.invoke('install-hexa-instance', data),
    deleteInstance: (folderName) => ipcRenderer.invoke('delete-instance', folderName),
    onGameExit: (callback) => ipcRenderer.on('game-exit', (event, code) => callback(code)),
    stopGame: () => ipcRenderer.invoke('stop-game'),
    openFolder: (folder) => ipcRenderer.invoke('open-folder', folder),
    createInstance: (data) => ipcRenderer.invoke('create-instance', data),
    applyCustomSkinLoader: (data) => ipcRenderer.invoke('apply-custom-skin-loader', data),
    fetchUsers: () => ipcRenderer.invoke('fetch-users'),
    addFriend: (username) => ipcRenderer.invoke('add-friend', username),
    fetchFriends: () => ipcRenderer.invoke('fetch-friends'),
    acceptFriend: (friendId) => ipcRenderer.invoke('accept-friend', friendId),
    rejectFriend: (friendId) => ipcRenderer.invoke('reject-friend', friendId),
    getMessages: (friendId) => ipcRenderer.invoke('get-messages', friendId),
    sendMessage: (friendId, message) => ipcRenderer.invoke('send-message', {friendId, message}),
    editMessage: (msgId, newContent) => ipcRenderer.invoke('edit-message', {msgId, newContent}),
    deleteMessage: (msgId) => ipcRenderer.invoke('delete-message', msgId),
    fetchImageBase64: (url) => ipcRenderer.invoke('fetch-image-base64', url),
    checkUpdate: () => ipcRenderer.invoke('check-update'),
    downloadUpdate: () => ipcRenderer.invoke('download-update'),
    onUpdateAvailable: (cb) => ipcRenderer.on('update-available', (e, info) => cb(info)),
    onUpdateProgress: (cb) => ipcRenderer.on('update-progress', (e, p) => cb(p)),
    onUpdateDownloaded: (cb) => ipcRenderer.on('update-downloaded', () => cb()),
});

